spring:
  application:
    name: javawebTest
  datasource:
    dynamic:
      primary: webtest
      datasource:
        webtest:
          url: jdbc:mysql://127.0.0.1:3306/webtest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: hzw123